#!/bin/sh

set -e


# remove path if exists
if [ -d /opt/maraschino ]; then
    rm -Rf /opt/maraschino
fi

# if git exists clone repo, else wget maraschino.tar.gz
if which git > /dev/null; then
    git clone https://github.com/mrkipling/maraschino.git /opt/maraschino
elif wget -O /tmp/maraschino.tar.gz https://nodeload.github.com/mrkipling/maraschino/tarball/master; then
    # create path again
    mkdir -p /opt/maraschino || exit 1
    tar -xzf /tmp/maraschino.tar.gz --strip 1 -C /opt/maraschino
    rm -f /tmp/maraschino.tar.gz
else
    echo "Both git clone and wget file failed, to solve this execute: 
    git clone https://github.com/mrkipling/maraschino.git /opt/maraschino
        or:
    wget -O /tmp/maraschino.tar.gz https://nodeload.github.com/mrkipling/maraschino/tarball/master && tar -xzf /tmp/maraschino.tar.gz --strip 1 -C /opt/maraschino
    
    or download, extract and copy the files from github to /opt/maraschino"
    exit 1
fi

# execute init.script
update-rc.d maraschino defaults  | grep /etc/init.d/maraschino
/etc/init.d/maraschino start
