#!/bin/sh

# remove stuff if purge
if [ $1 = 'purge' ]; then
    rm -f /etc/cron.hourly/mediafrontpage
    rm -f /etc/cron.daily/mediafrontpage
    rm -f /etc/cron.weekly/mediafrontpage
    rm -f /etc/cron.monthly/mediafrontpage
fi

