#!/bin/sh

# remove stuff if purge
if [ $1 = 'purge' ]; then
    /usr/sbin/update-rc.d -f headphones remove | grep /etc/init.d/headphones
    rm -f /etc/cron.hourly/headphones
    rm -f /etc/cron.daily/headphones
    rm -f /etc/cron.weekly/headphones
    rm -f /etc/cron.monthly/headphones
fi

