#!/bin/sh

set -e

# stop headphones
if pgrep -f Headphones.py > /dev/null; then
    /etc/init.d/headphones stop
fi

# make sure process is killed ok and pidfile is removed
if pgrep -f Headphones.py > /dev/null; then
    rm -f $(ps up $(pgrep -f Headphones.py) | grep pidfile | sed "s/.*--pidfile=//g") > /dev/null
    kill -9 $(pgrep -f Headphones.py) > /dev/null
fi

# remove path if exists
if [ -d /opt/headphones ]; then
    rm -Rf /opt/headphones
fi

