#!/bin/sh

set -e

# remove stuff if purge
if [ $1 = 'purge' ]; then
    [ -e /etc/cron.hourly/spotweb && rm -f /etc/cron.hourly/spotweb
    [ -e /etc/cron.daily/spotweb && rm -f /etc/cron.daily/spotweb
    [ -e /etc/cron.weekly/spotweb && rm -f /etc/cron.weekly/spotweb
    [ -e /etc/cron.monthly/spotweb && rm -f /etc/cron.monthly/spotweb
    [ -e /etc/cron.hourly/spotweb_spots ] && rm -f /etc/cron.hourly/spotweb_spots
fi

