#!/bin/sh

set -e

# remove stuff if purge
if [ $1 = 'purge' ]; then
    rm -f /etc/cron.hourly/spotweb
    rm -f /etc/cron.daily/spotweb
    rm -f /etc/cron.weekly/spotweb
    rm -f /etc/cron.monthly/spotweb
    rm -f /etc/cron.hourly/spotweb_spots
fi

