#!/bin/sh

set -e

# remove stuff if purge
if [ $1 = 'purge' ]; then
    /usr/sbin/update-rc.d -f couchpotato remove | grep /etc/init.d/couchpotato
    rm -f /etc/cron.hourly/couchpotato
    rm -f /etc/cron.daily/couchpotato
    rm -f /etc/cron.weekly/couchpotato
    rm -f /etc/cron.monthly/couchpotato
fi

