#!/bin/sh

set -e

# Stop couchpotato service.
# Stop couchpotato service.
if pgrep -f CouchPotato.py > /dev/null; then
    [ -e /etc/init.d/couchpotato ] && /etc/init.d/couchpotato stop
fi

