#!/bin/sh

set -e

# if git exists clone repo, else wget couchpotatov2.tar.gz
if which git > /dev/null; then
    git clone https://github.com/RuudBurger/CouchPotatoServer.git /opt/couchpotatov2
elif wget -O /tmp/couchpotatov2.tar.gz https://nodeload.github.com/RuudBurger/CouchPotatoServer/tarball/master; then
    # create path again
    mkdir -p /opt/couchpotatov2 || exit 1
    tar -xzf /tmp/couchpotatov2.tar.gz --strip 1 -C /opt/couchpotatov2
    rm -f /tmp/couchpotatov2.tar.gz
else
    echo "Both git clone and wget file failed, to solve this execute: 
    git clone https://github.com/RuudBurger/CouchPotatoServer.git /opt/couchpotatov2
        or:
    wget -O /tmp/couchpotatov2.tar.gz https://nodeload.github.com/RuudBurger/CouchPotatoServer/tarball/master && tar -xzf /tmp/couchpotatov2.tar.gz --strip 1 -C /opt/couchpotatov2
    
    or download, extract and copy the files from github to /opt/couchpotatov2"
    exit 1
fi

# execute init.script
update-rc.d couchpotatov2 defaults  | grep /etc/init.d/couchpotatov2
/etc/init.d/couchpotatov2 start
