#!/bin/sh

set -e

# Stop couchpotatov2 service.
# Stop couchpotatov2 service.
if pgrep -f CouchPotatoV2.py > /dev/null; then
    [ -e /etc/init.d/couchpotatov2 ] && /etc/init.d/couchpotatov2 stop
fi

# remove path if exists
if [ -d /opt/couchpotatov2 ]; then
    rm -Rf /opt/couchpotatov2
fi

